@startuml
title Catchpocket Operation

database Datomic #ivory [
  **Datomic**
  ....

  "" {:my-thing/attr ""
  ""  ...}""

]

package "Schema Generation" {
  node Catchpocket #lavenderblush [
    **Catchpocket CLI**
    ....
    ""lein generate""\n""catchpocket.edn""
  ]

  file CatchpocketConfig #azure [
    **""catchpocket.edn""**
    ....
    ""{:catchpocket/datomic-uri ""
    ""  "datomic:dev://..." ""
    "" :catchpocket/schema-file ""
    ""  "target/stillsuit.edn"}""
  ]

  file StillsuitConfig #ivory [
    **""stillsuit.edn""**
    ....
    ""{:objects ""
    "" {:MyThing""
    ""  {:fields ""
    ""   {:attr {...}}}}""
  ]

}

package "Runtime Execution" {
  component Stillsuit #ivory [
    **Stillsuit Library**
    ....
    ""(def compiled-schema ""
    ""  (stillsuit/decorate""
    ""   (load-edn "stillsuit.edn")))""

    ""(def app-context""
    ""  (stillsuit/app-context""
    ""   "datomic:dev://..."))""
  ]

  component Lacinia [
    **Lacinia Library**
    ....
    ""(lacinia/execute""
    "" compiled-schema""
    "" query ""
    "" app-context)""
  ]

  node Application #lavenderblush
  actor User
}

Datomic --> Stillsuit : runtime\nresolution
CatchpocketConfig --> Catchpocket

Lacinia -> Stillsuit
Application -> Lacinia

Datomic --> Catchpocket : schema\ngeneration
StillsuitConfig --> Stillsuit

Catchpocket -> StillsuitConfig

User -> Application : GraphQL\nQuery


@enduml
